// <auto-generated />
namespace Vehicle.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddVehicleTblVehicleRequestConfirmedTblVehicleRequestTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVehicleTblVehicleRequestConfirmedTblVehicleRequestTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202207210444214_AddVehicleTblVehicleRequestConfirmedTblVehicleRequestTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
